---
- hosts: localhost
  connection: local
  roles:
  
  - role: 'grycap.kubeminio'
    minio_secretkey: '{{ oscar_minio_secretkey }}'
    master_deploy: true
    enable_tls: true
    enable_ingress: true
    public_hostname: "{{ minio_dns_host }}"

  - role: 'grycap.kubefaas'

  - role: 'grycap.kubeoscar'
    oscar_pass: '{{ oscar_password }}'
    create_ingress: true
    minio_endpoint:  'https://{{ minio_dns_host }}'
    minio_secret_key: '{{ oscar_minio_secretkey }}'
    master_deploy: true
    openfaas_scaler_enable: true
    serverless_backend: "openfaas"
