---
- hosts: localhost
  connection: local
  roles:
  
  - role: 'grycap.kubeminio'
    minio_secretkey: '{{ oscar_minio_secretkey }}'
    master_deploy: true
    enable_tls: true

  - role: 'grycap.kubeoscar'
    oscar_pass: '{{ oscar_password }}'
    create_ingress: true
    minio_endpoint:  'https://{{ IM_NODE_PUBLIC_IP }}:30300'
    minio_secret_key: '{{ oscar_minio_secretkey }}'
    minio_tls_verify: false
    master_deploy: true
