---
- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
  roles:
  - role: grycap.nfs
    nfs_mode: 'wn'
  - role: 'grycap.kubernetes'
    kube_type_of_node: 'wn'
    kube_server: '{{kube_front_end_ip}}'
    kube_api_server: '{{ kube_front_end_ip }}'
    kube_nvidia_driver_version: "465"
