---
- hosts: localhost
  connection: local
  tasks:
  - name: Create temporary file
    tempfile:
      state: file
      suffix: .yaml
    register: tempfile

  - name: Change temporary file permissions
    file:
      path: "{{ tempfile.path }}"
      mode: 0644

  - name: Copy ansible tasks
    copy:
      content: "{{ ansible_tasks | to_nice_yaml }}"
      dest: "{{ tempfile.path }}"

  - name: Include tasks
    include_tasks:
      file: "{{ tempfile.path }}"
