---
- hosts: localhost
  connection: local
  tasks:
    - block:
      - name: Download dns_registry.py
        get_url:
          url: https://raw.githubusercontent.com/grycap/ec3/tosca/tosca/artifacts/dns_registry.py
          dest: /opt/dns_registry.py
          mode: 0755

      - name: Install pip and setuptools Py3
        package: name=python3-setuptools,python3-pip
        when: ansible_python.version.major > 2

      - name: Install pip and setuptools
        package: name=python-setuptools,python-pip
        when: ansible_python.version.major <= 2

      - name: Install boto3
        pip: name=boto3

      - name: Register DNS record
        shell: python /opt/dns_registry.py create {{ dns_service }} "{{ dns_service_credentials["token"] }}" {{ record_name }} {{ domain_name }} {{ ip_address }} > /opt/dns_registry_{{record_name}}.out
        args:
          creates: /opt/dns_registry_{{record_name}}.out

      when: record_name != ""
