---
- hosts: localhost
  connection: local
  vars:
    kubeconfig_path: '/etc/kubernetes/admin.conf'
    jup_auth_class: "{{ authenticator_class | default('dummy') }}"
    jup_dummy_pass: "{{ dummy_pass | default('dummy_pass') }}"
  tasks:
  - name: Add jupyterhub helm repo
    command: helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"

  - name: "Update helm repositories"
    command: helm repo update
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"

  - name: "Create values file"
    copy:
      dest: /tmp/config.yaml
      content: |
          hub:
            baseUrl: /jupyterhub
          proxy:
            service:
              type: ClusterIP
          auth:
            type: {{ jup_auth_class }}
            admin:
              access: true
              users:
                - admin
            dummy:
              password: {{ jup_dummy_pass }}
            whitelist:
              users:
          ingress:
            annotations: { kubernetes.io/ingress.class: nginx }
            enabled: true
            #pathSuffix: jupyterhub

  - name: Install (or upgrade) the chart
    command: helm upgrade --install jupyterhub jupyterhub/jupyterhub --namespace jupyter --create-namespace --values /tmp/config.yaml
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"
