- hosts: local
  connection: local
  vars:
    NAMESPACE: ai-sprint-monitoring
    REGISTRY: https://registry.gitlab.polimi.it
    DNS_BASE_NAME: "{{ dns_name | default('ai-sprint.local') }}"
  tasks:
  - name: Create the ai-sprint-monitoring ns file spec
    copy:
      content: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{NAMESPACE}}
      dest: /tmp/ai_ns.yml

  - name: Create ai-sprint-monitoring ns
    command: kubectl apply -f /tmp/ai_ns.yml
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Create registry credentials
    command: kubectl create secret docker-registry registry-credentials --docker-server={{ REGISTRY }} --docker-username={{ GITLAB_REGISTRY_TOKEN }} --docker-password={{ GITLAB_REGISTRY_TOKEN }} --docker-email={{ GITLAB_REGISTRY_EMAIL }} --namespace={{ NAMESPACE }}
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    ignore_errors: yes

  - name: Download monitoring-subsystem git repo
    git:
      repo: "https://{{ GITLAB_REPO_TOKEN }}:{{ GITLAB_REPO_TOKEN }}@gitlab.polimi.it/ai-sprint/monitoring-subsystem.git"
      dest: /opt/monitoring-subsystem
      version: master

  - name: Install Helm Chart
    copy:
      dest: /tmp/ai-values.yml
      content: |
        grafana:
          ingress:
            enabled: true
            hosts:
              - grafana.{{ DNS_BASE_NAME }}
            tls: []
            #  - secretName: chart-example-tls
            #    hosts:
            #      - chart-example.local
        influxdb:
          ingress:
            enabled: true
            hostname: influxdb.{{ DNS_BASE_NAME }}
            ## extraTls:
            ## - hosts:
            ##     - influxdb.local
            ##   secretName: influxdb.local-tls
          influxdb:
            service:
              nodePorts:
                http: 8086
          auth:
            admin:
              username: {{ admin_username }}
              password: {{ admin_password }}
              token: {{ admin_token }}
              org: {{ org_name }}
              bucket: {{ bucket_name }}
        elasticsearch:
          ingress:
            enabled: true
            hosts:
              - host: elasticsearch.{{ DNS_BASE_NAME }}
                paths:
                  - path: /
            tls: []
          volumeClaimTemplate:
            storageClassName: null
        kibana:
          ingress:
            enabled: true
            hosts:
              - host: kibana.{{ DNS_BASE_NAME }}
                paths:
                  - path: /
            tls: []

  - name: Install Helm Chart
    command: helm upgrade ai-sprint-monit-chart AI-Sprint-Monitoring-1.0.0.tgz --install -n {{ NAMESPACE }} -f /tmp/ai-values.yml
    args:
      chdir: /opt/monitoring-subsystem/deliverables
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

